### ISSUE TITLE
docs/example: delivery outside of SupplyChain

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#26]
> "I want to run my configured containers on k8s"

```
Given a customer who has used Cartographer to take a workload through a supply-chain to config
When they read Cartographer documentation
Then they confidently configure Kapp to deploy the config
```

### Problem  

Cartographer currently takes workloads and turns them into k8s configuration, ready to be deployed on a cluster. Customers need a paved road to actually do this deployment. We should tell customers how they can use Carvel tooling to achieve this goal.

### Acceptance Criteria
A Cartographer use case example of using Carvel to deploy and application

_(ported from docs repo)_

**Comment by cirocosta** [comment]
@emmjohnson and I had started working on this, which was more of a stop-gap  until Delivery gets built, but with the effort of actually getting that done, I believe we should put this one down.

wdy'all think?

**Comment by ekcasey** [comment]
Looking into this I think it would make sense to:
1. break up the [`deployer` component](https://github.com/vmware-tanzu/cartographer/blob/main/examples/source-to-knative-service/app-operator/supply-chain.yaml#L43-L49) in our current example into:
  * An `app-config` component that uses ytt in a ClusterTemplate to generate a ConfigMap containing k8s config
  * An `app-deploy` component that uses a ClusterTemplate to create a `kapp` app the directly reconciles against the config map ala
```
        fetch:
        - inline:
            pathsFrom:
              - configMapRef:
                name: $(workload.metadata.name)$
```

2. Then, show in another git-ops supply chain example how you can:
- replace one `templateRef` (app-deploy) with another (git-writer) to commit your config instead of deploying it
- configure a kapp App in another cluster to directly reconcile against the git repo

**Comment by waciumawanjohi** [comment]
possible todo: create some repo that is simply meant for writing arbitrary bits as an example. Since arbitrary things could be written, the name should make clear that it's an unsafe repository (users should assume that any code written there is malicious).
